services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   volumes:
  #     - redis_data:/data
  #   command: ["redis-server", "--appendonly", "yes"]
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20

  ws:
    build:
      context: ./apps/ws
      dockerfile: Dockerfile
    container_name: flowdesk-ws
    # depends_on:
    #   redis:
    #     condition: service_healthy
    ports:
      - "3020:3020"
    restart: always
    volumes:
      - ./apps/ws:/app
      - /app/node_modules
    env_file:
      - ./apps/ws/.env

volumes:
  redis_data: